source "https://rubygems.org"

ruby "~> 3.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"


# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# mac does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# CORSの設定
gem "rack-cors"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

# ローカル(開発・テスト)では MySQL を使う
group :development, :test do
  gem "mysql2", "~> 0.5"
  gem 'dotenv-rails'
end

# 本番(Render)では PostgreSQL (Neon) を使う
group :production do
  gem 'pg'
end


# パスワードを安全に保存するため
gem 'bcrypt'

# 認証トークン(JWT)を扱うため
gem 'jwt'

gem 'logger', '~> 1.7'