name: deploy-backend
on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch: {}

env:
  AWS_REGION: ap-northeast-1
  AWS_ACCOUNT_ID: 343218202623
  ECR_REPOSITORY: salon-rails-lambda
  LAMBDA_FUNCTION_NAME: salon-rails
  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::343218202623:role/GitHubActionsDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Build & Push (ECR)
        uses: docker/build-push-action@v6
        with:
          context: ./backend                 # フロントとバックで分けているせいで、指定しないと！！！
          file: ./backend/Dockerfile         # ここも
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update Lambda
        run: |
          IMAGE="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}"
          aws lambda update-function-code \
            --function-name "${LAMBDA_FUNCTION_NAME}" \
            --image-uri "${IMAGE}" \
            --region "${AWS_REGION}"
          aws lambda wait function-updated --function-name "${LAMBDA_FUNCTION_NAME}" --region "${AWS_REGION}"

      - name: Show new image (for sanity)
        run: |
          aws lambda get-function --function-name "${LAMBDA_FUNCTION_NAME}" --region "${AWS_REGION}" \
            --query '{ImageUri:Code.ImageUri,ResolvedImageUri:Code.ResolvedImageUri,LastModified:Configuration.LastModified}'
